databases:
  - name: jmm-db
    plan: free
    databaseName: jmm-db
    user: jmm

services:
  - type: web
    name: jmm-app
    env: java
    plan: free
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -jar target/base-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: PORT
        value: 8080
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: jmm-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: jmm-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: jmm-db
          property: password
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_PRICE_ID
        sync: false
